### ISSUE TITLE
Fix PyQt scaling issue

### ISSUE THREAD

**Issue by MariusAdrian88** [vispy/vispy#2189]
Hello,
I use VisPy module version 0.8.0, Python 3.9.4, PyQt6 6.1.1 on Windows 10 x64.
I have a problem that may have a easy solution but I can't see it due of not knowing enough of the VisPy and I need your help in solving this issue.

**The problem.**
If in Windows I use a scaling of anything different of 100% then I get the issue seen in the pictures (scaling at 125%):

![windows_scaling_125%](https://user-images.githubusercontent.com/40632281/130668695-bbae5159-3324-48fe-af7e-2bdc69ee1bf3.JPG)
![windows_scaling_125%_2](https://user-images.githubusercontent.com/40632281/130668725-5d26b03c-0953-46e5-a510-c82b8ebe0847.jpg)

**The setting is done here:**

![windows_scaling_setting](https://user-images.githubusercontent.com/40632281/130668780-1578a744-b302-48a5-82ba-c09e633fadc1.JPG)

**The way is supposed to look is like here (it is the result when running the example code with scaling 100%):**
![windows_scaling_100%](https://user-images.githubusercontent.com/40632281/130668900-a3e6714b-4884-486b-9a66-399841fe23dd.JPG)

I used this code:
```
from PyQt6.QtGui import QPalette, QScreen
from PyQt6 import QtCore, QtWidgets

import vispy.scene as scene
from vispy.scene.visuals import Rectangle, Text
from vispy.color import Color

import sys


class VisPyCanvas(scene.SceneCanvas):

    def __init__(self, config=None):
        super().__init__(config=config, keys=None)

        self.unfreeze()

        # Colors used by the Scene
        theme_color = Color('#FFFFFF')
        tick_color = Color('#000000')
        back_color = str(QPalette().color(QPalette.ColorRole.Window).name())

        # Central Widget Colors
        self.central_widget.bgcolor = back_color
        self.central_widget.border_color = back_color

        # Add a Grid Widget
        self.grid_widget = self.central_widget.add_grid(margin=10)
        self.grid_widget.spacing = 0

        # TOP Padding
        top_padding = self.grid_widget.add_widget(row=0, col=0, col_span=2)
        top_padding.height_max = 0

        # RIGHT Padding
        right_padding = self.grid_widget.add_widget(row=0, col=2, row_span=2)
        right_padding.width_max = 0

        # X Axis
        self.xaxis = scene.AxisWidget(
            orientation='bottom', axis_color=tick_color, text_color=tick_color,
            font_size=8, axis_width=1,
            anchors=['center', 'bottom']
        )
        self.xaxis.height_max = 30
        self.grid_widget.add_widget(self.xaxis, row=2, col=1)

        # Y Axis
        self.yaxis = scene.AxisWidget(
            orientation='left', axis_color=tick_color, text_color=tick_color,
            font_size=8, axis_width=1
        )
        self.yaxis.width_max = 55
        self.grid_widget.add_widget(self.yaxis, row=1, col=0)

        # View & Camera
        self.view = self.grid_widget.add_view(row=1, col=1, border_color=tick_color,
                                              bgcolor=theme_color)
        self.view.camera = scene.PanZoomCamera(aspect=1, rect=(-25, -25, 150, 150))

        self.xaxis.link_view(self.view)
        self.yaxis.link_view(self.view)

        # add GridLines
        self.grid = scene.GridLines(parent=self.view.scene, color='dimgray')
        self.grid.set_gl_state(depth_test=False)

        self.freeze()

        # self.measure_fps()


class PlotCanvas(QtCore.QObject):

    def __init__(self, container, my_app):
        """
        The constructor configures the VisPy figure that
        will contain all plots, creates the base axes and connects
        events to the plotting area.

        :param container: The parent container in which to draw plots.
        :rtype: PlotCanvas
        """

        super().__init__()

        # VisPyCanvas instance
        self.vispy_canvas = VisPyCanvas()

        self.vispy_canvas.unfreeze()

        self.my_app = my_app

        # Parent container
        self.container = container

        # <VisPyCanvas>
        self.vispy_canvas.create_native()
        self.vispy_canvas.native.setParent(self.my_app.ui)

        # <QtCore.QObject>
        self.container.addWidget(self.vispy_canvas.native)

        # add two Infinite Lines to act as markers for the X,Y axis
        self.v_line = scene.visuals.InfiniteLine(
            pos=0, color=(0.0, 0.0, 1.0, 0.3), vertical=True,
            parent=self.vispy_canvas.view.scene)

        self.h_line = scene.visuals.InfiniteLine(
            pos=0, color=(0.00, 0.0, 1.0, 0.3), vertical=False,
            parent=self.vispy_canvas.view.scene)

        self.vispy_canvas.freeze()

    def event_connect(self, event, callback):
        getattr(self.vispy_canvas.events, event).connect(callback)

    def event_disconnect(self, event, callback):
        getattr(self.vispy_canvas.events, event).disconnect(callback)

    def translate_coords(self, pos):
        """
        Translate pixels to canvas units.
        """
        tr = self.vispy_canvas.grid.get_transform('canvas', 'visual')
        return tr.map(pos)


class MyGui(QtWidgets.QMainWindow):
    screenChanged = QtCore.pyqtSignal(QScreen, QScreen)

    def __init__(self, app):
        super().__init__()

        self.setWindowTitle("VisPy Test")

        self.my_app = app

        # add Menubar
        self.menu = self.menuBar()
        self.menufile = self.menu.addMenu("File")
        self.menuedit = self.menu.addMenu("Edit")
        self.menufhelp = self.menu.addMenu("Help")

        # add a Toolbar
        self.file_toolbar = QtWidgets.QToolBar("File Toolbar")
        self.addToolBar(self.file_toolbar)
        self.button = self.file_toolbar.addAction("Open")

        # add Central Widget
        self.c_widget = QtWidgets.QWidget()
        self.central_layout = QtWidgets.QVBoxLayout()
        self.c_widget.setLayout(self.central_layout)
        self.setCentralWidget(self.c_widget)

        # add InfoBar
        self.infobar = self.statusBar()
        self.position_label = QtWidgets.QLabel("Position:  X: 0.0000\tY: 0.0000")
        self.infobar.addWidget(self.position_label)

        self.screenChanged.connect(self.on_screen_change)

    def on_screen_change(self, old_screen, new_screen):
        """
        Handler of a signal that emits when screens are changed in a multi-monitor setup

        :param old_screen:  QtGui.QScreen where the app windows was located before move
        :param new_screen:  QtGui.QScreen where the app windows is located after move
        :return:
        """
        old_pixel_ratio = old_screen.devicePixelRatio()
        new_pixel_ratio = new_screen.devicePixelRatio()

        if old_pixel_ratio != new_pixel_ratio:
            # update canvas dpi
            ratio = new_pixel_ratio / old_pixel_ratio
            self.my_app.plot.vispy_canvas.dpi = self.my_app.plot.vispy_canvas.dpi * ratio

    def moveEvent(self, event):
        oldScreen = QtWidgets.QApplication.screenAt(event.oldPos())
        newScreen = QtWidgets.QApplication.screenAt(event.pos())

        if not oldScreen == newScreen:
            self.screenChanged.emit(oldScreen, newScreen)

        return super().moveEvent(event)


class MyApp(QtCore.QObject):

    def __init__(self):
        super().__init__()

        self.ui = MyGui(app=self)
        self.plot = PlotCanvas(container=self.ui.central_layout, my_app=self)

        self.ui.show()

        self.plot.event_connect(event="mouse_move", callback=self.on_mouse_move)

    def on_mouse_move(self, event):
        cursor_pos = event.pos

        pos_canvas = self.plot.translate_coords(cursor_pos)

        # we don't need all the info in the tuple returned by the translate_coords()
        # only first 2 elements
        pos_canvas = [pos_canvas[0], pos_canvas[1]]
        self.ui.position_label.setText("Position:  X: %.4f\tY: %.4f" % (pos_canvas[0], pos_canvas[1]))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    m_app = MyApp()
    sys.exit(app.exec())

```

As it can be seen I've subclassed he QMainWindow, created a Qt signal named screenChanged which is emitted when the screen is changed.
This is done by overloading the MoveEvent where it detects the screen change and it will emit this signal.
In the slot connected to this signal, **on_screen_change(self, old_screen, new_screen)** I am attempting to change the DPI and it look like I get the result but the scene where the gridlines are displayed is not changed to reflect the new size of the Qt central widget.

I am appreciating any help with how to solve this issue.

Thank you,
Marius

**Comment by djhoese** [comment]
The Qt backends have their own handling of screen changes here:

https://github.com/vispy/vispy/blob/1c85d407eb617305c3689bdd0b0dfc31ad7e3186/vispy/app/backends/_qt.py#L422-L431

Looks like your slot (the method you are connecting) accepts two parameters. The VisPy backend is only expecting one. Maybe Qt6 allows for 1 or 2 parameter versions to be connected to this, or maybe it changed in Qt6 and this isn't actually being called. Theoretically VisPy is supposed to handle the screen change all itself (or at least that's what we want, right?).

It is also possible you are causing a race condition between the VisPy screen change handler running and your dpi handler changing.

**Comment by mars0001** [comment]
@djhoese 
Hi David,

I arrived to this new signal when I saw that in a multi-monitor situation, one monitor with HD resolution, 125% scaling and the second monitor 2k resolution, 100% scaling.

When I am in the second monitor, with 100% scaling, all is OK. If I drag the application window to the first monitor (with 125% scaling) then I get the issue with the scene not resizing. But if I get it back then the screen goes back to normal.

First thing I thought about the DPI. I saw that going from one screen to another did not change the DPI as it was supposed to (larger fonts). 
I thought to handle this from PyQt so I searched for a solution to detect on which screen I am into and print it's DPI with a QT method and the DPI detected by VisPy. 

This is how I arrived to adding this **custom** Qt signal, screenChanged. By using it I saw that the Qt reported different DPI values for each screen (a difference of 125% like it was in the Windows settings) but VisPy reported the same DPI (I used a method from Canvas class from VisPy) regardless of the screen I was into.

But then, I tested the same thing using a single monitor configuration and I just changed the scaling to 125% and I saw the same visual issue. So it is not related to a multi-monitor setup, it looks like VisPy is no longer sensing the scaling.

Sorry to making this more complicated that it was supposed to. Perhaps I should have left not added the part with the custom signal screenChanged.

So the problem is that VisPy is not autodetecting scaling. Could you test the example above and see if you get the same? It may be the same problem for Linux too.

Best regards,
Marius

**Comment by mars0001** [comment]
I've made a screen capture:
![scaling-issue](https://user-images.githubusercontent.com/40632281/130677447-63158123-89da-4d3b-853d-21b8752d602e.gif)

**Comment by djhoese** [comment]
So your example as is didn't run for me. I got:

```
WARNING: Traceback (most recent call last):
  File "/home/davidh/repos/git/vispy/vispy_support/issue_2189.py", line 171, in on_screen_change
    old_pixel_ratio = old_screen.devicePixelRatio()
AttributeError: 'NoneType' object has no attribute 'devicePixelRatio'
Aborted (core dumped)
```

Add a `if old_screen is None: return` let me run it. I have both my displays at 100% but when I bumped the second one to 125% then I saw the same issue. Note I'm also on PopOS (Ubuntu) so this isn't Windows specific. One thing to check would be if this is an issue in PyQt5 too.

**Comment by djhoese** [comment]
I have a fix! One second...

**Comment by djhoese** [comment]
```diff

===================================================================
diff --git a/vispy/app/backends/_qt.py b/vispy/app/backends/_qt.py
--- a/vispy/app/backends/_qt.py	(revision 5d0f7b4d625153da7b4215fd255b30205fbec2d1)
+++ b/vispy/app/backends/_qt.py	(date 1629833319343)
@@ -878,7 +878,7 @@
             # We take into account devicePixelRatio, which is non-unity on
             # e.g HiDPI displays.
             # self.devicePixelRatio() is a float and should have been in Qt5 according to the documentation
-            ratio = int(self.devicePixelRatio())
+            ratio = self.devicePixelRatio()
             w = w * ratio
             h = h * ratio
         self._vispy_set_physical_size(w, h)
```

Fixes it for me with no screen change in the main program needed.

**Comment by djhoese** [comment]
Sorry, this is probably more accurate:

```diff
===================================================================
diff --git a/vispy/app/backends/_qt.py b/vispy/app/backends/_qt.py
--- a/vispy/app/backends/_qt.py	(revision 5d0f7b4d625153da7b4215fd255b30205fbec2d1)
+++ b/vispy/app/backends/_qt.py	(date 1629833459326)
@@ -878,9 +878,9 @@
             # We take into account devicePixelRatio, which is non-unity on
             # e.g HiDPI displays.
             # self.devicePixelRatio() is a float and should have been in Qt5 according to the documentation
-            ratio = int(self.devicePixelRatio())
-            w = w * ratio
-            h = h * ratio
+            ratio = self.devicePixelRatio()
+            w = int(w * ratio)
+            h = int(h * ratio)
         self._vispy_set_physical_size(w, h)
         self._vispy_canvas.events.resize(size=(self.width(), self.height()),
                                          physical_size=(w, h))

```

**Comment by mars0001** [comment]
:) I've added a try - except AttributeError clause myself.

With PyQt 5.14.4 (latest version in PyPi) there are no issues.
![scaling-qt5 14](https://user-images.githubusercontent.com/40632281/130678713-03c41f60-24b0-4965-861b-79858eb89e65.gif)

**Comment by mars0001** [comment]
> Sorry, this is probably more accurate:
> 
> ```diff
> ===================================================================
> diff --git a/vispy/app/backends/_qt.py b/vispy/app/backends/_qt.py
> --- a/vispy/app/backends/_qt.py	(revision 5d0f7b4d625153da7b4215fd255b30205fbec2d1)
> +++ b/vispy/app/backends/_qt.py	(date 1629833459326)
> @@ -878,9 +878,9 @@
>              # We take into account devicePixelRatio, which is non-unity on
>              # e.g HiDPI displays.
>              # self.devicePixelRatio() is a float and should have been in Qt5 according to the documentation
> -            ratio = int(self.devicePixelRatio())
> -            w = w * ratio
> -            h = h * ratio
> +            ratio = self.devicePixelRatio()
> +            w = int(w * ratio)
> +            h = int(h * ratio)
>          self._vispy_set_physical_size(w, h)
>          self._vispy_canvas.events.resize(size=(self.width(), self.height()),
>                                           physical_size=(w, h))
> ```

That looks like it solved the issue, just adding a minor artifact... Thank you!
![scaling-qt6-solved](https://user-images.githubusercontent.com/40632281/130679424-4fc8de1d-003e-49a2-802f-95581354748b.gif)

**Comment by almarklein** [comment]
FWIW, we did cast scaling to ints earlier on this line:

**Comment by djhoese** [comment]
@almarklein So you're saying that the fix for this issue is likely one you were trying to solve when you made that similar change in the rfb PR?

**Comment by almarklein** [comment]
No, I meant that I thought that I had fixed support for non-integer pixel ratio's but I had overlooked any int-casts in the backends.

**Comment by mars0001** [comment]
Hi,
The contributor that added the VisPy to the app I'm working on also created some patches for VisPy that are applied at the app start (adding a new MarkerVisual, making the labels on Axis Widget less dense, optimizing the performance impact of using AxisWidget) and I added the David's fix to those patches.
Therefore the issue is solved for me until the next version release of VisPy.

Thank you all!

**Comment by djhoese** [comment]
@mars0001 Do you have the time to submit my patch as a pull request since you were the one who had the original problem and tested it more thoroughly?

As for the patches, would you or your coworker mind submitting these as pull requests? I think there was an issue recently or maybe even a pull request by someone who wanted something similar for the axis ticks. The new marker seems easy enough to add too. Would be great to have these additions upstream in vispy and available to everyone. Thanks.

**Comment by mars0001** [comment]
@djhoese 
Hi David,
The InfiniteLine visual may need a different approach to make it configurable, here is hardcoded to 1 ... 2 pixels. We may need a property.
For the rest I could do that, sure. 

BTW,  I saw that you are happy with having classes like in matplotlib so what do you think to add a new class where we can have as input Shapely 2D geometric features (polygons, linearrings, linestrings) and then paint them on canvas? The contributor that I was talking about added that feature (including tesselation) a few years back. I tried to contact him some time ago but he didn't answer so I guess we could use his work (Hayrullin Denis Ravilevich) and give him credits in a comment.
Thank you!

**Comment by djhoese** [comment]
> including tesselation

Interesting. I've done something similar in my own work with reading shapefiles from NaturalEarth and plotting them. I'd be open to that. @kmuehlbauer I think has suggested something similar (if I'm remembering correctly).
