### ISSUE TITLE
examples/tutorial/gl/fireworks.py doesn't work on OS X

### ISSUE THREAD

**Issue by nippoo** [vispy/vispy#837]
Shows a black screen on any backend...

**Comment by campagnola** [comment]
Looks ok to me. Can you do a git-bisect?

**Comment by nippoo** [comment]
@campagnola are you on OS X?

**Comment by campagnola** [comment]
OF COURSE NOT.
;)

**Comment by Eric89GXL** [comment]
Ahh good call, I can verify it works back on https://github.com/vispy/vispy/tree/5dc34f10323c7a35b35a6f8351587541fd2bf3bf/examples/rawgl two years ago, bisecting now

**Comment by Eric89GXL** [comment]
The commit was mine:

https://github.com/vispy/vispy/commit/bf27284ce1399ca0a83d91113610bdebd1f86a12

Apparently deleting the `#version 120` was a problem... putting back in made it work for me. Commit made. @nippoo can you check at your end?

**Comment by nippoo** [comment]
Works great for me! `git bisect`-a-licious.

Just running the tests now.

**Comment by nippoo** [comment]
Still get:

```
    def glGetProgramInfoLog(program):
        res = GL.glGetProgramInfoLog(program)
>       return res.decode('utf-8')
E       AttributeError: 'str' object has no attribute 'decode'
```

as well as the ton of `max_corr` errors. The other two are gone though!

**Comment by almarklein** [comment]
> 'str' object has no attribute 'decode'

This looks like PyOpenGL now produces a str instead of bytes. What version of PyOpenGL do you have? There was a new release like a month ago.

**Comment by almarklein** [comment]
Continuuing discussion on `str.decode` on #838
