### PR TITLE
Complex volume - Continued

### PR DESCRIPTION
**Pull request by brisvag**
Picking up the work in #2314; refer to that for previous discussion.

This PR introduces a new `ComplexVolumeVisual` which mirrors the implementation of the `ComplexImageVisual`: it takes complex data as input, and provides an extra `complex_mode` attribute that controls how that complex data is transformed into a single scalar. The options (and their respective glsl computation) are:
```glsl
    "real": "float cplx2float(vec4 data) { return data.r; }",
    "imaginary": "float cplx2float(vec4 data) { return data.g; }",
    "magnitude": "float cplx2float(vec4 data) { return length(data.rg); }",
    "phase": "float cplx2float(vec4 data) { return atan(data.g, data.r); }",
```

The added examples shows what this looks like:

image

You can press 1 to switch volume rendering mode (`mip` etc), and 2 to switch complex mode.

### CODE REVIEW

**Comment by brisvag** [comment]
I think that either we merge this as it is (after adding tests), or we modify both `Image` and `Volume` to account for `ComplexImage`, dropping the subclass approach. I kinda prefer the second... In that case, we can also deprecate `ComplexImage` by simply pointing to `Image` itself :shrug:

**Comment by djhoese** [comment]
It'd be easier if ImageVisual wasn't as complex (not the data type) as it is. I think maintaining either implementation has pros and cons so whoever wants to do the work gets to choose.

**Comment by aganders3** [comment]
This is great to see. I am interested if there is a way to unify this with some experiments I have done with 2D transfer functions for volume rendering. The idea basically being that we could move a lot of this logic into something like a 2D colormap with a glsl snippet, instead of being part of the visual itself.

**Comment by brisvag** [comment]
Are you suggesting to basically have the `color2scalar2` snippet settable? Or more something more sphisticated?

**Comment by brisvag** [comment]
Interesting... Sounds pretty cool! But this maybe should be handled as a followup PR in case? I don't think we're necessarily making it easier or harder with this PR?

**Comment by aganders3** [comment]
Yeah that's fair enough - sorry for the noise in that case, I just got excited because it seemed related! What I described might cover the behavior from this PR, but I can appreciate the value in making it simple to do common things (users shouldn't have to write GLSL to just show the magnitude of some complex data). I will polish up what I have to get it ready for a separate PR.

**Comment by aganders3** [comment]
In the meantime I'll add a couple comments on this PR :).

Note `colorToScalar` is doing the same work as `colorToVal`. I prefer the name `colorToScalar` so I suggest you remove `colorToVal` and replace its usage.
https://github.com/vispy/vispy/blob/bac8c074388f65ea464aa5e4c3d8106de24575bd/vispy/visuals/volume.py#L124C7-L127

I also prefer dropping the `Complex*` subclasses as you suggested.

Finally a tiny nit - I would add a way to toggle the `complex_mode` in the example.

**Comment by brisvag** [comment]
No worries, it's good to make sure that we don't mess up possible future/better ideas :package: 

All great suggestions, thanks!

**Comment by roflmaostc** [comment]
What's the current state of complex numbers in Napari?

**Comment by brisvag** [comment]
Hey @roflmaostc! The current state is: not implemented :P Indeed, we should get this PR finished and released, and then expose in in napari in a followup.

Actually, I'm happy to pick this up again if there's demand for it :) Woudl you like to open an issue on the napari repo, tag this PR, and maybe give an example of your use case? This way we can discuss it over there.

**Comment by jni** [comment]
I'd be very excited to see this over the finish line!

**Comment by roflmaostc** [comment]
I see someone's working on this, very cool :)
If I can buy a coffee for some of you, let me know!

**Comment by brisvag** [comment]
Hey @roflmaostc! That won't be necessary, but thanks for the encouragement :muscle: If you could play with it and test some real data you have and report back, that would super useful! It's currently looking like there's some bug in the shader, based on the example, but I'll circle back to it soon :)

**Comment by brisvag** [comment]
Maybe working now? :thinking: @jni if you could also play with it that would be great!

**Comment by brisvag** [comment]
Ok, NOW it actually works I think. There was a nasty bug in the texture internalformat logic that ended up magically setting the format to `rgg32f` instead of the given `rg32f`, because it was replacing *just* the `r` with `rg`... Somehow this went unnoticed until now o.o

**Comment by TimMonko** [comment]
Hey @matthiasschabel! Have you ever looked at the Vispy repo? I barely have 😆 It's the rendering engine for napari's visuals.

I wanted to ping you here for your expertise -- this enables complex image rendering in 3D -- because we do not have much experience with complex images. Would you be able to try this out with your data (sticking it into the example would be the easiest way to test) _or_ just using your knowledge to review this and see if this addresses your needs.

**Comment by matthiasschabel** [comment]
> Hey @matthiasschabel! Have you ever looked at the Vispy repo? I barely have 😆 It's the rendering engine for napari's visuals.
> 
> I wanted to ping you here for your expertise -- this enables complex image rendering in 3D -- because we do not have much experience with complex images. Would you be able to try this out with your data (sticking it into the example would be the easiest way to test) _or_ just using your knowledge to review this and see if this addresses your needs.

I haven't really delved into vispy yet - nothing I've run into has been that far upstream... Happy to have a look! What type of feedback are you specifically interested in?

**Comment by TimMonko** [comment]
The core feedback needed is "does this make sense" and "will it actually work for people". I think we just don't have experts using this, but @brisvag should be able to give a better answer on what he's looking for :)

**Comment by brisvag** [comment]
Mainly, if you have *real* complex data that you can make sense of, it would be great if yu could stick it into the example and look at it, and tell me if it's correct and looks like you'd expect. I see "stuff" and there are no code bugs, but I don't know if the stuff I see is correct xD

**Comment by matthiasschabel** [comment]
@brisvag @TimMonko 

The path getting complex data into the GPU looks correct to me, and the wrap-aware phase gradient in COMPLEX_GRADIENTS is the right idea.

The main challenge with complex data is handling phase consistently: using a cyclic colormap that avoids a visual discontinuity at the ±pi boundary, and accounting for the fact that the significance of the phase depends on the magnitude. Phase should always be limited on (-pi,pi) - I don't think it makes sense to window it 

I don't think this PR currently supports the most likely case, which is mapping amplitude to brightness/alpha and phase to hue (that's what napari#7890 is asking for). Right now applyColormap takes a vec4 and immediately collapses it to a float via $colorToScalar; you want to be able to use the whole vec4 in the color transform so magnitude and phase can drive separate channels.

I'm not sure all the blending operations make sense, or can make sense, for complex data. This isn't a typical presentation for MRI so I'd have to think about it more. Average accumulates the raw vec4 and collapses afterwards, so it computes |mean(z)|, the coherent mean, not mean(|z|). The docstring calls it "average intensity projection", which is a different operation.

volume.py:818 sets the default iso threshold to vol.mean(), but by that point vol is the interleaved (D,H,W,2) float view, so the default is the mean of the real and imaginary parts together, which I don't think it what we want here.

**Comment by brisvag** [comment]
> you want to be able to use the whole vec4 in the color transform so magnitude and phase can drive separate channels.

Right... This reminds me a bit of https://github.com/vispy/vispy/pull/2550... I think we're hitting on similar nails here: we basically need an ability to take arbitrary operations that take rgba texture and go to rgba color output.

> I'm not sure all the blending operations make sense, or can make sense, for complex data.

I wouldn't worry too muich about this; It's ok if some combinations are nonsensical (to us, there's always someone out there who finds a use for anything xD), as long as we get some useful paths. I don't see a reason to *disable* them, or worse to special case and create even more beanching in an already extremely complicated shader.

I'm wondering at this point is we shoul "just merge" this just so we get a mirroring implementation for `image` and for `volume`, and then try to do this more generally?

**Comment by matthiasschabel** [comment]
This PR breaks napari on my MacBook: 

napari's `_vispy/visuals/volume.py` copies `VolumeVisual._shaders['fragment']`, splices its own gradient and shading functions in ahead of `void main()`, and those functions call `colorToVal`. Removing `colorToVal` leaves the spliced code referencing an undeclared identifier, so the fragment shader fails to compile for every 3D render, `mip` included. 

```python
import numpy as np
from vispy import scene
from napari._vispy.visuals.volume import Volume

canvas = scene.SceneCanvas(size=(200, 200), show=False)
view = canvas.central_widget.add_view()
view.camera = scene.cameras.ArcballCamera(parent=view.scene, fov=60)
Volume(np.zeros((16, 16, 16), np.float32), parent=view.scene, texture_format='auto')
canvas.render()
```

```
RuntimeError: Shader compilation error in GL_FRAGMENT_SHADER:
    on line 361: Invalid call of undeclared identifier 'colorToVal'
      prev = colorToVal(texture_lookup(prev_loc));
```

Same script works on 0.16.2. Renaming downstream call sites to `$colorToScalar` fails on 0.16.2 with `Unsubstituted placeholders in code: ['$colorToScalar', ...]` and then a syntax error on `float $colorToScalar(vec4 color1)`. I think this is a fix:

```glsl
float colorToVal(vec4 color1)
{
    // Deprecated, use $colorToScalar
    return $colorToScalar(color1);
}
```

**Comment by brisvag** [comment]
This is expected @matthiasschabel: we use internal/private stuff of vispy in napari, and that's why we have an upper pin on vispy versions other than bugfix releases. Once this is merged, we'll release as a non-bugfix, and napari will *not* grab it automatically. I'll then open a PR in napari that bumps the pins and updates the code to match the new name!

**Comment by brisvag** [comment]
Since this is still having issues and it mighty require more work, I'm gonna go ahead and do already a release with the current PRs!
