### ISSUE TITLE
hello_fbo.py doesn't work on Retina MBP OS X 10.8

### ISSUE THREAD

**Issue by nippoo** [vispy/vispy#21]
Error:

```
$ python hello_fbo.py 
Error compiling shader <FragmentShader 'textured fragment shader'>
    on line 8: '/' does not operate on 'float' and 'int'
        float scalefactor = 1.0 / (c_sze * c_sze * 4 + 1);
    on line 14: Use of undeclared identifier 'scalefactor'
        gl_FragColor.rgb += color * scalefactor;
Traceback (most recent call last):
  File "hello_fbo.py", line 117, in on_paint
    with self._program2 as prog:
  File "/Users/nippoo/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vispy/oogl/__init__.py", line 87, in __enter__
    self._enable()
  File "/Users/nippoo/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vispy/oogl/program.py", line 158, in _enable
    self._enable_shaders()
  File "/Users/nippoo/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vispy/oogl/program.py", line 220, in _enable_shaders
    shader._enable()
  File "/Users/nippoo/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vispy/oogl/shader.py", line 94, in _enable
    raise RuntimeError(errors)
RuntimeError: ERROR: 0:8: '/' does not operate on 'float' and 'int'
ERROR: 0:14: Use of undeclared identifier 'scalefactor'
```
