### ISSUE TITLE
basics/visuals/colored_line example doesn't work on Python 3.4

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#524]
```
AttributeError: 'itertools.cycle' object has no attribute 'next'
```
