### ISSUE TITLE
Depth testing broken for some mesh Nodes

### ISSUE THREAD

**Issue by inclement** [vispy/vispy#871]
This can be seen in master in the basics/visuals/tube.py example.

I bisected the problem to the introduction of set_gl_state for the Visual class, and I think the actual cause is that MeshVisual and Node both call `Visual.__init__(...)`, but Node does so second. This overwrites the MeshVisual setting (enabling depth testing) with the default.

In testing, I found that e.g. replacing the relevant `Visual.__init__` line with the following made things seem to work as normal, to demonstrate the issue.

    if not hasattr(self, '_gl_state'):
        self._gl_state = {'preset': None}

However, I don't understand why this issue doesn't seem to affect the other examples using scene.visual classes, such as basics/scene/isosurface.py

**Comment by Eric89GXL** [comment]
Could it be fixed by switching the `Node` super-class `__init__` to occur before the `Mesh` `set_gl_state` calls instead of after? @campagnola if you have an idea of the correct answer here feel free to jump in.

**Comment by inclement** [comment]
@Eric89GXL I tried this by switching the order in the constructed `__init__` method of vispy/scene/visuals.py, but it doesn't work - running the tube example gives

    Traceback (most recent call last):
      File "tube.py", line 59, in <module>
        canvas.view.add(l1)
      File "/home/asandy/devel/vispy/vispy/scene/widgets/viewbox.py", line 182, in add
        node.add_parent(self.scene)
      File "/home/asandy/devel/vispy/vispy/scene/node.py", line 148, in add_parent
        self.events.parents_change(added=parent)
    AttributeError: 'EmitterGroup' object has no attribute 'parents_change'

I think this is a similar problem, the Node adds these events to itself but then self.events is overridden by the MeshVisual's own `__init__`.

**Comment by Eric89GXL** [comment]
Ahh, so it's a more general problem than just `gl_state` then. Somehow we need to make it so that either `Node` respects what is done by its subclasses and have `Node.__init__` run at the end of the subclass `__init__`, or the subclasses need to respect what `Node` does and do `Node.__init__` at the beginning of each subclass `__init__`. I'm fine either way. @campagnola WDYT?

**Comment by campagnola** [comment]
I have already fixed this in a branch I am working on.
