### ISSUE TITLE
Tiny error in basics/plotting/plot.py 

### ISSUE THREAD

**Issue by dderiso** [vispy/vispy#1325]
Thanks for the great library!

I was just running though the examples when I found  tiny bug. When I run the [basics/plotting/plot](https://github.com/vispy/vispy/blob/master/examples/basics/plotting/plot.py) example,

    python3.6 vispy_plot.py

I observe this error.

    INFO: Could not import backend "PyQt4":
    No module named 'PyQt4'
    Traceback (most recent call last):
      File "vispy_plot.py", line 21, in <module>
        ylabel='4/π Σ[ 1/n sin(nπx/L) | n=1,3,5,...]')
    TypeError: plot() got an unexpected keyword argument 'title'

Hope this helps

**Comment by thomasaarholt** [comment]
I just ran into the same bug trying the same example:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-84f2c9d3cb7b> in <module>()
     19 y = np.cos(x)
     20 line = fig[0, 0].plot((x, y), symbol='o', width=3, title='I/V Curve',
---> 21                       xlabel='Current (pA)', ylabel='Membrane Potential (mV)')
     22 grid = vp.visuals.GridLines(color=(0, 0, 0, 0.5))
     23 grid.set_gl_state('translucent')

TypeError: plot() got an unexpected keyword argument 'title'
```

**Comment by kmuehlbauer** [comment]
Obviously you are both working with the last vispy release 0.4.0. The `title`-keyword was introduced after release of 0.4.0. Please use the latest from github master branch.

Both examples run fine on linux with python3.6.

**Comment by thomasaarholt** [comment]
Thanks. Will try it out!

**Comment by dderiso** [comment]
Thanks, that fixed it. For anyone else encountering this, make sure to uninstall first.

    # uninstall 
    sudo -H pip3.6 uninstall vispy
    
    # install latest version
    git clone https://github.com/vispy/vispy.git
    cd vispy
    sudo -H python3.6 setup.py install

**Comment by kmuehlbauer** [comment]
@davidh-ssec This is resolved and can be closed.

**Comment by kmuehlbauer** [comment]
@dderiso Good to hear it works. @thomasaarholt Does that fix it also on your side?

Closing as resolved.
